// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Readioo.Data.Data.Contexts;

#nullable disable

namespace Readioo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130135014_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Readioo.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Readioo.Models.AuthorGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthorId" }, "IX_AuthorGenres_AuthorId");

                    b.HasIndex(new[] { "GenreId" }, "IX_AuthorGenres_GenreId");

                    b.ToTable("AuthorGenres");
                });

            modelBuilder.Entity("Readioo.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainCharacters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthorId" }, "IX_Books_AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Readioo.Models.BookGenre", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres");
                });

            modelBuilder.Entity("Readioo.Models.BookShelf", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ShelfId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "ShelfId");

                    b.HasIndex("ShelfId");

                    b.ToTable("BookShelves");
                });

            modelBuilder.Entity("Readioo.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore the limitless possibilities of the universe. From space operas and alien civilizations to cybernetic futures and time travel, these stories ask the ultimate 'what if' questions about technology and humanity.",
                            GenreName = "Science Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Prepare to be terrified. These spine-chilling tales explore the darker side of existence, featuring supernatural entities, psychological torments, and the unknown, designed to keep you on the edge of your seat and awake at night.",
                            GenreName = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Enter worlds where society has collapsed or turned oppressive. These gripping narratives explore survival, rebellion, and the resilience of the human spirit amidst totalitarian regimes, environmental disasters, or post-apocalyptic ruins.",
                            GenreName = "Dystopian"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Escape into realms of magic, myth, and adventure. Whether it’s epic quests to save a kingdom, battles with dragons, or subtle magical realism, these stories weave folklore and imagination into unforgettable journeys.",
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fast-paced and adrenaline-fueled, these books are impossible to put down. Packed with high stakes, dangerous chases, and shocking plot twists, thrillers keep you guessing untill the very last page.",
                            GenreName = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Put on your detective hat and solve the puzzle. From classic whodunits and noir investigations to cozy village secrets, these stories revolve around crime, clues, and the thrill of uncovering the truth.",
                            GenreName = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dive deep into the complexities of the human experience. These emotionally resonant stories focus on realistic characters, interpersonal conflicts, and the triumphs and tragedies of everyday life.",
                            GenreName = "Drama"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Travel back in time to experience different eras. Meticulously researched and atmospherically rich, these novels transport readers to the past, blending real events with fictional lives to bring history to life.",
                            GenreName = "Historical"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Explore the corridors of power and the mechanisms of governance. These narratives critique societal structures, expose corruption, and delve into the ideologies that shape nations and revolutions.",
                            GenreName = "Political"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Immerse yourself in the art of long-form storytelling. These works of fiction prioritize character development and narrative depth, offering a profound exploration of themes that resonate with the human condition.",
                            GenreName = "Novel"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Discover the true stories behind the names. These accounts offer intimate looks into the lives of historical figures, innovators, and cultural icons, providing inspiration and insight through their struggles and achievements.",
                            GenreName = "Biography"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Challenge your perspective and expand your mind. These works delve into the fundamental nature of knowledge, reality, ethics, and existence, encouraging deep contemplation on the meaning of life.",
                            GenreName = "Philosophy"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Step into the shadowy world of lawbreakers and law enforcement. Focusing on the perpetrators, the victims, and the investigators, these gritty tales explore the motives behind criminal acts and the quest for justice.",
                            GenreName = "Crime"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Perfect for quick escapes, these collections offer bite-sized narratives that pack a punch. Ranging from experimental vignettes to fully realized tales, they capture distinct moments and emotions in a concise format.",
                            GenreName = "Short Stories"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A sharp wit meets social commentary. Using humor, irony, and exaggeration, these clever stories expose the absurdities of society, politics, and human behavior, making you think while you laugh.",
                            GenreName = "Satire"
                        });
                });

            modelBuilder.Entity("Readioo.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BookId" }, "IX_Reviews_BookId");

                    b.HasIndex(new[] { "UserId" }, "IX_Reviews_UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Readioo.Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ShelfName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_shelves_UserId");

                    b.ToTable("shelves", (string)null);
                });

            modelBuilder.Entity("Readioo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProfileURL");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UserImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Readioo.Models.UserBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BookId" }, "IX_UserBooks_BookId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserBooks_UserId");

                    b.ToTable("UserBooks");
                });

            modelBuilder.Entity("Readioo.Models.UserGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GenreId" }, "IX_UserGenres_GenreId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserGenres_UserId");

                    b.ToTable("UserGenres");
                });

            modelBuilder.Entity("Readioo.Models.AuthorGenre", b =>
                {
                    b.HasOne("Readioo.Models.Author", "Author")
                        .WithMany("AuthorGenres")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Readioo.Models.Genre", "Genre")
                        .WithMany("AuthorGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Readioo.Models.Book", b =>
                {
                    b.HasOne("Readioo.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Readioo.Models.BookGenre", b =>
                {
                    b.HasOne("Readioo.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Readioo.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Readioo.Models.BookShelf", b =>
                {
                    b.HasOne("Readioo.Models.Book", "Book")
                        .WithMany("BookShelves")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Readioo.Models.Shelf", "Shelf")
                        .WithMany("BookShelves")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Readioo.Models.Review", b =>
                {
                    b.HasOne("Readioo.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Readioo.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Readioo.Models.Shelf", b =>
                {
                    b.HasOne("Readioo.Models.User", "User")
                        .WithMany("Shelves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Readioo.Models.UserBook", b =>
                {
                    b.HasOne("Readioo.Models.Book", "Book")
                        .WithMany("UserBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Readioo.Models.User", "User")
                        .WithMany("UserBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Readioo.Models.UserGenre", b =>
                {
                    b.HasOne("Readioo.Models.Genre", "Genre")
                        .WithMany("UserGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Readioo.Models.User", "User")
                        .WithMany("UserGenres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Readioo.Models.Author", b =>
                {
                    b.Navigation("AuthorGenres");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("Readioo.Models.Book", b =>
                {
                    b.Navigation("BookGenres");

                    b.Navigation("BookShelves");

                    b.Navigation("Reviews");

                    b.Navigation("UserBooks");
                });

            modelBuilder.Entity("Readioo.Models.Genre", b =>
                {
                    b.Navigation("AuthorGenres");

                    b.Navigation("BookGenres");

                    b.Navigation("UserGenres");
                });

            modelBuilder.Entity("Readioo.Models.Shelf", b =>
                {
                    b.Navigation("BookShelves");
                });

            modelBuilder.Entity("Readioo.Models.User", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Shelves");

                    b.Navigation("UserBooks");

                    b.Navigation("UserGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
